// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package store

import (
	"context"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
	task,
	done
) 
VALUES(?, ?)
RETURNING id, task, done
`

type CreateTodoParams struct {
	Task string
	Done int64
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.Task, arg.Done)
	var i Todo
	err := row.Scan(&i.ID, &i.Task, &i.Done)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT id, task, done
FROM todos
`

func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(&i.ID, &i.Task, &i.Done); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET task = ?, done = ?
WHERE id = ?
RETURNING id, task, done
`

type UpdateTodoParams struct {
	Task string
	Done int64
	ID   int64
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodo, arg.Task, arg.Done, arg.ID)
	var i Todo
	err := row.Scan(&i.ID, &i.Task, &i.Done)
	return i, err
}
