// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package store

import (
	"context"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
	task,
	done
) 
VALUES(?, ?)
RETURNING id, task, done
`

type CreateTodoParams struct {
	Task string
	Done int64
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.Task, arg.Done)
	var i Todo
	err := row.Scan(&i.ID, &i.Task, &i.Done)
	return i, err
}
